package Game_operator;

public enum UpdateCode {
    ATTENTE,
    INIT_NUMBER_PLAYER,
    INIT_NUMBER_BOT,
    ERROR_NUMBER,
    INIT_NAME_PLAYER,
    INIT_DIFFICULTY_BOT,
    ERROR_DIFFICULTY,

    GAME_INIT_ROUND,
    CHOOSE_IDENTITY,
    END_CHOOSE_IDENTITY,

    GAME_ROUND,
    ACCUSE_OR_PLAY,
    ACCUSE,
    END_ACCUSATION,
    IS_ACCUSED,
    IS_REVEALED,

    PLAY_CARD_HUNT,
    PLAY_CARD_WITCH,

    END_PLAY,

}
