package Game_operator;

public enum UpdateCode {
    ATTENTE,
    INIT_NUMBER_PLAYER,
    INIT_NUMBER_BOT,
    ERROR_NUMBER,
    INIT_NAME_PLAYER,
    INIT_DIFFICULTY_BOT,
    ERROR_DIFFICULTY,
    GAME_INIT_ROUND,
    GAME_ROUND,
    ROUND_MANAGEMENT;
}
